use crate::codegen::value::Value;
use crate::codegen::CodeGen;
use crate::hir::Type;
use inkwell::values::{BasicValue, BasicValueEnum};
use inkwell::AddressSpace;

impl<'ctx> CodeGen<'ctx> {
    /// Generates the LLVM IR for a literal.
    ///
    /// Literals always return an R-Value. This is because literals are always
    /// immutable and cannot be assigned to.
    pub(super) fn generate_literal_r_value(&self, value: &str, ty: &Type) -> Value<'ctx> {
        let literal_value = match ty {
            Type::Int => self
                .context
                .i32_type()
                .const_int(Self::int_value(value), false)
                .as_basic_value_enum(),
            Type::Int64 => self
                .context
                .i64_type()
                .const_int(Self::int_value(value), false)
                .as_basic_value_enum(),
            Type::Int128 => todo!(),
            Type::Int256 => todo!(),
            Type::Float => self
                .context
                .f32_type()
                .const_float(value.parse::<f32>().unwrap() as f64)
                .as_basic_value_enum(),
            Type::Float64 => self
                .context
                .f64_type()
                .const_float(value.parse::<f64>().unwrap())
                .as_basic_value_enum(),
            Type::Bool => self
                .context
                .bool_type()
                .const_int(Self::bool_value(value), false)
                .as_basic_value_enum(),
            Type::String => self.generate_string_literal(value),
            Type::Unit => unimplemented!("unit type"),
            Type::Array(_) => todo!(),
            Type::Struct(_) => unimplemented!("Structs are generated by struct literals"),
            Type::Enum(_) => todo!(),
            Type::Error(_) => todo!(),
            Type::Generic(_, _) => todo!(),
            Type::DeclaredGeneric(_) => todo!(),
        };

        Value::new(self.to_basic_type_enum(ty).unwrap(), literal_value)
    }

    /// Detects base and converts a string to an integer value.
    fn int_value(value: &str) -> u64 {
        if let Some(stripped) = value.strip_prefix("0x") {
            u64::from_str_radix(stripped, 16).unwrap()
        } else if let Some(stripped) = value.strip_prefix("0o") {
            u64::from_str_radix(stripped, 8).unwrap()
        } else if let Some(stripped) = value.strip_prefix("0b") {
            u64::from_str_radix(stripped, 2).unwrap()
        } else {
            value.parse().unwrap()
        }
    }

    /// Converts a string to a boolean value.
    fn bool_value(value: &str) -> u64 {
        match value {
            "true" => 1,
            "false" => 0,
            // This should be verified by the type checker.
            _ => unreachable!("Invalid boolean value. File a bug report - error in type checker"),
        }
    }

    /// Generates a string literal, returning the original struct.
    fn generate_string_literal(&self, value: &str) -> BasicValueEnum<'ctx> {
        let ptr_type = self.context.ptr_type(AddressSpace::default());
        let i64_type = self.context.i64_type();

        let string_length_llvm_int = self.context.i32_type().const_int(value.len() as u64, false);

        // CartString: { i32, i32, i8* }
        let cart_string_llvm_type = self.context.struct_type(
            &[
                i64_type.into(), // Reference count
                i64_type.into(), // Length
                ptr_type.into(), // Pointer to string data
            ],
            false,
        );

        let cart_string_ptr = self.create_entry_block_alloca(
            cart_string_llvm_type,
            format!("cart_string_{}_ptr", value).as_str(),
        );

        // Initialize reference count to 1:
        let ref_count_gep = self
            .builder
            .build_struct_gep(
                cart_string_llvm_type,
                cart_string_ptr,
                0,
                format!("ref_count_gep_{}", value).as_str(),
            )
            .unwrap();
        self.builder
            .build_store(ref_count_gep, i64_type.const_int(1, false))
            .unwrap()
            .set_alignment(8)
            .unwrap();

        // Initialize length:
        let length_gep = self
            .builder
            .build_struct_gep(
                cart_string_llvm_type,
                cart_string_ptr,
                1,
                format!("length_gep_{}", value).as_str(),
            )
            .unwrap();
        self.builder
            .build_store(length_gep, i64_type.const_int(value.len() as u64, false))
            .unwrap()
            .set_alignment(8)
            .unwrap();

        // Initialize string data:
        let char_arr = self
            .builder
            .build_array_malloc(
                self.context.i8_type(),
                string_length_llvm_int,
                format!("bytes_array_{}", value).as_str(),
            )
            .unwrap();

        // Now, char_arr is a pointer to the allocated memory. Copy the string into it.
        for (i, byte) in value.bytes().enumerate() {
            let gep_idx = i64_type.const_int(i as u64, false);
            let byte_ptr = unsafe {
                self.builder
                    .build_gep(
                        self.context.i8_type(),                    // Points to a byte
                        char_arr,   // The pointer to the allocated memory
                        &[gep_idx], // The index of the byte
                        format!("byte_{}", byte as char).as_str(), // name
                    )
                    .expect("Could not build GEP")
            };
            self.builder
                .build_store(
                    byte_ptr,
                    self.context.i8_type().const_int(byte as u64, false),
                )
                .unwrap_or_else(|_| panic!("Could not store string byte {}", byte));
        }

        let data_gep = self
            .builder
            .build_struct_gep(cart_string_llvm_type, cart_string_ptr, 2, "data_gep")
            .unwrap();
        self.builder
            .build_store(data_gep, char_arr)
            .unwrap()
            .set_alignment(8)
            .unwrap();

        let cart_string = self
            .builder
            .build_load(
                cart_string_llvm_type,
                cart_string_ptr,
                "cart_string_literal_load",
            )
            .unwrap();

        cart_string
    }
}
