name: Build and Release Cart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-22.04, macos-13, macos-14 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LLVM
        id: llvm-install
        run: |
          if [[ "${{ matrix.os }}" == *"ubuntu"* ]]; then
            sudo apt-get update
            wget https://apt.llvm.org/llvm.sh && \
              chmod u+x llvm.sh && \
              sudo ./llvm.sh 18 && \
              sudo apt install -y libpolly-18-dev libz-dev
            echo "LLVM_SYS_PREFIX=/usr/lib/llvm-18" >> $GITHUB_OUTPUT
          else
            brew install llvm@18 zstd
            echo "LLVM_SYS_PREFIX=$(brew --prefix llvm@18)" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Cart
        env:
          LLVM_SYS_PREFIX: ${{ steps.llvm-install.outputs.LLVM_SYS_PREFIX }}
        run: |
          export LLVM_SYS_181_PREFIX=${LLVM_SYS_PREFIX}
          if [[ "${{ matrix.os }}" == *"macos"* ]]; then
            export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix zstd)/lib"
          fi
          cargo build --release

      - name: Package Files
        run: |
          mkdir -p dist/bin dist/lib
          cp target/release/cart dist/bin/
          cp target/release/libcartstd.a dist/lib/
          tar -czf cartlang-${{ matrix.os }}.tar.gz -C dist .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cart-build-${{ matrix.os }}
          path: cartlang-${{ matrix.os }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact for ubuntu-latest x86_64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-ubuntu-22.04

      - name: Download Artifact for macos-latest x86_64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-macos-13

      - name: Download Artifact for macos-latest arm64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-macos-14

      - name: Rename Files
        run: |
          mv cartlang-ubuntu-22.04.tar.gz cartlang-ubuntu-x86_64.tar.gz
          mv cartlang-macos-13.tar.gz cartlang-macos-x86_64.tar.gz
          mv cartlang-macos-14.tar.gz cartlang-macos-arm64.tar.gz

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            cartlang-ubuntu-x86_64.tar.gz
            cartlang-macos-x86_64.tar.gz
            cartlang-macos-arm64.tar.gz
          body: "Release of Cart Compiler version ${{ github.ref_name }}."
          tag: ${{ github.ref_name }}
