name: Build and Release Cart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        arch: [ x86_64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LLVM
        id: llvm-install
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            wget https://apt.llvm.org/llvm.sh && \
              chmod u+x llvm.sh && \
              sudo ./llvm.sh 18 && \
              sudo apt install -y libpolly-18-dev libz-dev
            echo "LLVM_SYS_PREFIX=/usr/lib/llvm-18" >> $GITHUB_OUTPUT
          else
            brew install llvm@18 zstd
            echo "LLVM_SYS_PREFIX=$(brew --prefix llvm@18)" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Cart
        env:
          LLVM_SYS_PREFIX: ${{ steps.llvm-install.outputs.LLVM_SYS_PREFIX }}
        run: |
          export LLVM_SYS_180_PREFIX=${LLVM_SYS_PREFIX}
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix zstd)/lib"
            cargo build --release --target ${{ matrix.arch }}-apple-darwin
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cargo build --release --target ${{ matrix.arch }}-unknown-linux-gnu
          fi

      - name: Package Files
        run: |
          mkdir -p dist/bin dist/lib
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp target/${{ matrix.arch }}-apple-darwin/release/cart dist/bin/
            cp target/${{ matrix.arch }}-apple-darwin/release/libcartstd.a dist/lib/
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            cp target/${{ matrix.arch }}-unknown-linux-gnu/release/cart dist/bin/
            cp target/${{ matrix.arch }}-unknown-linux-gnu/release/libcartstd.a dist/lib/
          fi
          tar -czf cartlang-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C dist .

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cart-build-${{ matrix.os }}-${{ matrix.arch }}
          path: cartlang-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact for ubuntu-latest x86_64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-ubuntu-latest-x86_64

      - name: Download Artifact for ubuntu-latest arm64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-ubuntu-latest-arm64

      - name: Download Artifact for macos-latest x86_64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-macos-latest-x86_64

      - name: Download Artifact for macos-latest arm64
        uses: actions/download-artifact@v4
        with:
          name: cart-build-macos-latest-arm64

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            cartlang-ubuntu-latest-x86_64.tar.gz
            cartlang-ubuntu-latest-arm64.tar.gz
            cartlang-macos-latest-x86_64.tar.gz
            cartlang-macos-latest-arm64.tar.gz
          body: "Release of Cart Compiler version ${{ github.ref_name }}."
          tag: ${{ github.ref_name }}