name: Build and Release Cart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        arch: [ x86_64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install LLVM
        id: llvm-install
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            wget https://apt.llvm.org/llvm.sh && \
              chmod u+x llvm.sh && \
              sudo ./llvm.sh 18 && \
              sudo apt install -y libpolly-18-dev libz-dev
            echo "LLVM_SYS_PREFIX=/usr/lib/llvm-18" >> $GITHUB_OUTPUT
          else
            brew install llvm@18
            echo "LLVM_SYS_PREFIX=$(brew --prefix llvm@18)" >> $GITHUB_OUTPUT
          fi

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Cart
        env:
          LLVM_SYS_PREFIX: ${{ steps.llvm-install.outputs.LLVM_SYS_PREFIX }}
        run: |
          export LLVM_SYS_180_PREFIX=${LLVM_SYS_PREFIX}
          cargo build --release

      - name: Package Files
        run: |
          mkdir -p dist/bin dist/lib
          cp target/release/cart dist/bin/
          cp target/release/libcartstd.a dist/lib/
          tar -czf cartlang-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C dist .

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cartlang-${{ github.ref_name }}-ubuntu-latest-x86_64.tar.gz
            cartlang-${{ github.ref_name }}-ubuntu-latest-arm64.tar.gz
            cartlang-${{ github.ref_name }}-macos-latest-x86_64.tar.gz
            cartlang-${{ github.ref_name }}-macos-latest-arm64.tar.gz
          body: "Release of Cart Compiler version ${{ github.ref_name }}."
          token: ${{ secrets.GITHUB_TOKEN }}
